#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8760/eureka
  instance:
    prefer-ip-address: true
    #每间隔10s，向服务端发送一次心跳，证明自己依然”存活“
    lease-renewal-interval-in-seconds: 2
    #告诉服务端，如果我20s之内没有给你发心跳，就代表我“死”了，
    #将我踢出掉。
    lease-expiration-duration-in-seconds: 3


spring:
  application:
    name: eureka-client1

server:
  port: 8762

EUREKA-CLIENT2:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
